"""Shared CLI paths and parser helpers."""

from __future__ import annotations

from fanpage_agent.cli_commands.parser import (
    DEFAULT_CALENDAR_FILE,
    DEFAULT_CAMPAIGN_FILE,
    DEFAULT_COMMENT_FILE,
    DEFAULT_HERMES_CRON_JOBS_FILE,
    DEFAULT_HERMES_SCRIPTS_DIR,
    DEFAULT_HISTORY_FILE,
    DEFAULT_METRICS_FILE,
    DEFAULT_TRIAGE_FILE,
    EXPECTED_HERMES_CRON_JOBS,
    OPS_ARTIFACT_FRESHNESS_HOURS,
    ROOT_DIR,
    add_store_backend_arg,
)

__all__ = [
    "DEFAULT_CALENDAR_FILE",
    "DEFAULT_CAMPAIGN_FILE",
    "DEFAULT_COMMENT_FILE",
    "DEFAULT_HERMES_CRON_JOBS_FILE",
    "DEFAULT_HERMES_SCRIPTS_DIR",
    "DEFAULT_HISTORY_FILE",
    "DEFAULT_METRICS_FILE",
    "DEFAULT_TRIAGE_FILE",
    "EXPECTED_HERMES_CRON_JOBS",
    "OPS_ARTIFACT_FRESHNESS_HOURS",
    "ROOT_DIR",
    "add_store_backend_arg",
]
